# Generated by Django 3.0 on 2020-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shippingcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billingName',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
