# Generated by Django 2.2.4 on 2020-06-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(default=0)),
                ('alt_no', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('pincode', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
